### ISSUE TITLE
Call to libarchive fails with "Failed to clean up compressor" on Windows

### ISSUE THREAD

**Issue by carterbox** [conda-forge/conda-package-handling-feedstock#63]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I'm trying to use conda-build in a[ Windows Docker container](https://github.com/conda-forge/docker-images/pull/209), but whenever I try to build a package, it fails during the packaging step. The error message is as below:

```bash
Packaging humanize
INFO:conda_build.build:Packaging humanize
Packaging humanize-4.0.0-py_0
INFO:conda_build.build:Packaging humanize-4.0.0-py_0
number of files: 63
Fixing permissions
Packaged license file/s.
INFO :: Time taken to mark (prefix)
        0 replacements in 0 files was 0.09 seconds
Traceback (most recent call last):
  File "C:\Users\Administrator\miniconda3\Scripts\conda-build-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\Administrator\miniconda3\lib\site-packages\conda_build\cli\main_build.py", line 488, in main
    execute(sys.argv[1:])
  File "C:\Users\Administrator\miniconda3\lib\site-packages\conda_build\cli\main_build.py", line 477, in execute
    outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
  File "C:\Users\Administrator\miniconda3\lib\site-packages\conda_build\api.py", line 186, in build
    return build_tree(
  File "C:\Users\Administrator\miniconda3\lib\site-packages\conda_build\build.py", line 3088, in build_tree
    packages_from_this = build(metadata, stats,
  File "C:\Users\Administrator\miniconda3\lib\site-packages\conda_build\build.py", line 2371, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "C:\Users\Administrator\miniconda3\lib\site-packages\conda_build\build.py", line 1692, in bundle_conda
    conda_package_handling.api.create(metadata.config.host_prefix, files,
  File "C:\Users\Administrator\miniconda3\lib\site-packages\conda_package_handling\api.py", line 88, in create
    raise err
  File "C:\Users\Administrator\miniconda3\lib\site-packages\conda_package_handling\api.py", line 82, in create
    out = SUPPORTED_EXTENSIONS[ext].create(prefix, file_list, out_fn, out_folder, **kw)
  File "C:\Users\Administrator\miniconda3\lib\site-packages\conda_package_handling\tarball.py", line 160, in create
    out_file = create_compressed_tarball(prefix, file_list, out_folder,
  File "C:\Users\Administrator\miniconda3\lib\site-packages\conda_package_handling\tarball.py", line 88, in create_compr
essed_tarball
    _create_libarchive(fullpath, files, compression_filter, filter_opts)
  File "C:\Users\Administrator\miniconda3\lib\site-packages\conda_package_handling\tarball.py", line 74, in _create_liba
rchive
    archive_utils.create_archive(fullpath, files, compression_filter, filter_opts)
  File "C:\Users\Administrator\miniconda3\lib\site-packages\conda_package_handling\archive_utils.py", line 29, in create
_archive
    raise ArchiveCreationError(message)
conda_package_handling.exceptions.ArchiveCreationError: Failed to clean up compressor
```

The error is from the conda-package-handling wrapper of libarchive which is statically linked. BUT why do I think this is a build error? Because, if I install conda-package-handling from defaults (same version), packaging completes successfully. So, it seems that the problem is unique to this build.

### Installed packages

```shell
# packages in environment at C:\Users\Administrator\miniconda3:
#
# Name                    Version                   Build  Channel
beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
brotlipy                  0.7.0           py39hb82d6ee_1004    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2021.10.8            h5b45459_0    conda-forge
certifi                   2021.10.8        py39hcbf5309_2    conda-forge
cffi                      1.15.0           py39h0878f49_0    conda-forge
chardet                   4.0.0            py39hcbf5309_3    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
conda                     4.12.0           py39hcbf5309_0    conda-forge
conda-build               3.21.8           py39hcbf5309_0    conda-forge
conda-package-handling    1.8.1            py39hb3671d1_1    conda-forge
console_shortcut          0.1.1                         4
cryptography              36.0.2           py39h7bc7c5c_1    conda-forge
filelock                  3.6.0              pyhd8ed1ab_0    conda-forge
git                       2.35.2               h57928b3_0    conda-forge
glob2                     0.7                        py_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
jinja2                    3.1.1                    pypi_0    pypi
libarchive                3.5.2                hb45042f_1    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
liblief                   0.11.5               h0e60522_1    conda-forge
libxml2                   2.9.13               hf5bbc77_0    conda-forge
libzlib                   1.2.11            h8ffe710_1014    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
lzo                       2.10              he774522_1000    conda-forge
m2-msys2-runtime          2.5.0.17080.65c939c               3    conda-forge
m2-patch                  2.7.5                         2    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markupsafe                2.1.1                    pypi_0    pypi
menuinst                  1.4.18           py39hcbf5309_1    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
openssl                   1.1.1n               h8ffe710_0    conda-forge
pip                       22.0.4             pyhd8ed1ab_0    conda-forge
pkginfo                   1.8.2              pyhd8ed1ab_0    conda-forge
powershell_shortcut       0.0.1                         3
psutil                    5.9.0            py39hb82d6ee_1    conda-forge
py-lief                   0.11.5           py39h415ef7b_1    conda-forge
pycosat                   0.6.3           py39hb82d6ee_1010    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py39hcbf5309_5    conda-forge
python                    3.9.12          h9a09f29_1_cpython    conda-forge
python-libarchive-c       4.0              py39hcbf5309_1    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
pywin32                   303              py39hb82d6ee_0    conda-forge
pyyaml                    6.0                      pypi_0    pypi
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
ripgrep                   13.0.0               h7f3b576_2    conda-forge
ruamel_yaml               0.15.80         py39hb82d6ee_1006    conda-forge
setuptools                62.1.0           py39hcbf5309_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
soupsieve                 2.3.1              pyhd8ed1ab_0    conda-forge
sqlite                    3.38.2               h8ffe710_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
tqdm                      4.64.0             pyhd8ed1ab_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
urllib3                   1.26.9             pyhd8ed1ab_0    conda-forge
vc                        14.2                 hb210afc_6    conda-forge
vs2015_runtime            14.29.30037          h902a5da_6    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0            py39hcbf5309_4    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
zlib                      1.2.11            h8ffe710_1014    conda-forge
zstd                      1.5.2                h6255e5f_0    conda-forge
```

### Environment info

```shell
active environment : base
    active env location : C:\Users\Administrator\miniconda3
            shell level : 1
       user config file : C:\Users\ContainerAdministrator\.condarc
 populated config files : C:\Users\ContainerAdministrator\.condarc
          conda version : 4.12.0
    conda-build version : 3.21.8
         python version : 3.9.12.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\Administrator\miniconda3  (writable)
      conda av data dir : C:\Users\Administrator\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Administrator\miniconda3\pkgs
                          C:\Users\ContainerAdministrator\.conda\pkgs
                          C:\Users\ContainerAdministrator\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Administrator\miniconda3\envs
                          C:\Users\ContainerAdministrator\.conda\envs
                          C:\Users\ContainerAdministrator\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.12 Windows/10 Windows/10.0.17763
          administrator : True
             netrc file : None
           offline mode : False
```

**Comment by dholth** [comment]
This bug belonged in the conda/conda-package-handling repository, but, it will be fixed with the 2.0 release which drops libarchive.
